### ISSUE TITLE
RimWorld-en

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#18]
Could you please create and maintain a folder of natural English version of the game on Github, so that it would be more convenient for translators to see the changes and react on them? Plus, it would be a lot easier, if the code framework would have been done by you and we only had to change the actual language stuff ;)
(If there is such a folder, could you please show it?, and I'm sorry to bother you) )

**Comment by Louisthebadassrimworlder** [comment]
Hey Diamond, can I ask how I am to upload certain files onto the GitHub page?






Sent from Windows Mail





From: Dimonasdf
Sent: ‎Thursday‎, ‎10‎ ‎September‎ ‎2015 ‎17‎:‎31
To: Ludeon/RimWorld-ru





Could you please create and maintain a folder of natural English version of the game on Github, so that it would be more convenient for translators to see the changes and react on them? Plus, it would be a lot easier, if the code framework would have been done by you and we only had to change the actual language stuff ;)
(If there is such a folder, could you please show it?, and I'm sorry to bother you) )

**Comment by Dimonasdf** [comment]
I've actually just realised, that there is no way to do so without Git client xD
I hope there is at least some way to do so with a client, but I don't know for sure since I haven't installed it.

**Comment by Dimonasdf** [comment]
Ладно, я понял. Судя по прилагающейся документации для переводчиков никто и не собирается этим заниматься.
